BEGIN;
CREATE FUNCTION pg_temp.check_true(ok boolean,message text) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION '%',message; END IF; END$$;
CREATE FUNCTION pg_temp.check_error(q text,code text) RETURNS void LANGUAGE plpgsql AS $$BEGIN BEGIN EXECUTE q; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=code THEN RETURN; END IF; RAISE; END; RAISE EXCEPTION 'Expected error %: %',code,q; END$$;
CREATE FUNCTION pg_temp.uid(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$SELECT ('e8210000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid$$;
GRANT EXECUTE ON FUNCTION pg_temp.check_true(boolean,text),pg_temp.check_error(text,text),pg_temp.uid(integer) TO authenticated,anon;
SELECT pg_temp.check_true((SELECT r.booking_id=o.booking_id AND r.rating=o.rating AND r.comment=o.comment AND r.review_scope='legacy_relationship' FROM public.reviews r JOIN pc_reviews_before o USING(id)),'Legacy review rewritten or reclassified');
SELECT pg_temp.check_true(NOT EXISTS(SELECT 1 FROM pc_private.service_review_threads WHERE review_scope='booking_service'),'Retrospective invitation');
SELECT pg_temp.check_true((SELECT bool_and(rating=0 AND review_count=0) FROM public.professionals),'General reputation still derived');
INSERT INTO public.bookings(id,owner_id,professional_id,service_id,start_at,end_at,status)
SELECT pg_temp.uid(n),pg_temp.uid(o),pg_temp.uid(p),pg_temp.uid(s),now()-interval '2 days',now()-interval '1 day','pending'
FROM (VALUES(401,4,5,205),(402,4,5,207),(403,4,5,205),(404,4,5,206),(405,4,2,203),(406,4,2,201),
 (407,4,2,201),(408,4,3,204),(409,1,5,205),(410,4,5,205),(411,4,5,205),(412,4,5,205)) v(n,o,p,s);
UPDATE public.bookings SET start_at=now()+interval '1 day',end_at=now()+interval '25 hours' WHERE id=pg_temp.uid(410);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(5)::text,true);
SELECT public.change_booking_status(pg_temp.uid(410),'accepted');
SELECT pg_temp.check_error($q$SELECT public.change_booking_status(pg_temp.uid(410),'completed')$q$,'PCR01');
SELECT public.change_booking_status(pg_temp.uid(411),'declined');
-- Boarding cannot count as the first lesson and cannot invite the centre to rate a client.
SELECT public.change_booking_status(pg_temp.uid(404),'accepted');SELECT public.change_booking_status(pg_temp.uid(404),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=0,'Boarding invited professional');
SELECT public.change_booking_status(pg_temp.uid(401),'accepted');SELECT public.change_booking_status(pg_temp.uid(401),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=1,'First lesson prompted after boarding');
SELECT public.change_booking_status(pg_temp.uid(402),'accepted');
RESET ROLE;
UPDATE public.services SET name='Nome cambiato',service_type='boarding' WHERE id=pg_temp.uid(207);
SET LOCAL ROLE authenticated;
SELECT public.change_booking_status(pg_temp.uid(402),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=1,'Second lesson at centre missing');
CREATE TEMP TABLE review_ids AS SELECT (x->>'id')::uuid AS id,(x->>'booking_id')::uuid AS booking_id FROM jsonb_array_elements(public.get_my_service_reviews(true)->'items') x;
RESET ROLE; GRANT ALL ON review_ids TO authenticated;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_true((SELECT x->>'service_name'='Corso nel centro' FROM jsonb_array_elements(public.get_my_service_reviews()->'items') x WHERE x->>'booking_id'=pg_temp.uid(402)::text),'Accepted service title changed');
SELECT pg_temp.check_error($q$SELECT public.submit_review(pg_temp.uid(401),5,'first lesson')$q$,'PCR02');
SELECT public.write_service_review(id,0,4,'La lezione prenotata',pg_temp.uid(701)) FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT public.write_service_review(id,0,4,'La lezione prenotata',pg_temp.uid(701)) FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,3,%L,%L)',id,'different',pg_temp.uid(701)),'22023') FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,3,%L,%L)',id,'stale',pg_temp.uid(702)),'40001') FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT public.write_service_review(id,1,5,'Rettifica della stessa lezione',pg_temp.uid(702)) FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT public.write_service_review(id,0,3,'Il soggiorno',pg_temp.uid(703)) FROM review_ids WHERE booking_id=pg_temp.uid(404);
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(5)::text,true);
SELECT public.write_service_review(id,0,2,'',pg_temp.uid(704)) FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,5,%L,%L)',id,'',pg_temp.uid(705)),'42501') FROM review_ids WHERE booking_id=pg_temp.uid(404);
SELECT public.change_booking_status(pg_temp.uid(403),'accepted');SELECT public.change_booking_status(pg_temp.uid(403),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=1,'Third lesson lacks its separate invitation');
RESET ROLE;
SELECT pg_temp.check_true((SELECT r.booking_id=pg_temp.uid(402) AND r.rating=5 AND r.comment='Rettifica della stessa lezione' FROM public.reviews r WHERE booking_id=pg_temp.uid(402)),'New lesson moved the previous review');
SELECT pg_temp.check_true((SELECT count(*)=3 FROM pc_private.service_review_threads WHERE professional_id=pg_temp.uid(5) AND review_scope='booking_service'),'Not one thread per eligible booking');
SELECT pg_temp.check_true((SELECT previous_value->>'comment'='La lezione prenotata' FROM pc_private.service_review_writes WHERE request_id=pg_temp.uid(702)),'Revision lost');
SELECT pg_temp.check_true((SELECT rating=0 AND review_count=0 FROM public.professionals WHERE id=pg_temp.uid(5)),'Lesson produced a centre rating');
SELECT pg_temp.check_error($q$UPDATE public.reviews SET booking_id=pg_temp.uid(403) WHERE booking_id=pg_temp.uid(402)$q$,'23514');
UPDATE pc_private.service_review_threads SET owner_edit_until=now()-interval '1 minute' WHERE latest_booking_id=pg_temp.uid(402);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,2,1,%L,%L)',id,'too late',pg_temp.uid(706)),'PCR03') FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT public.submit_review(pg_temp.uid(403),1,'Nuova lezione, nuovo giudizio');
SELECT public.submit_review(pg_temp.uid(403),1,'Nuova lezione, nuovo giudizio');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(1)::text,true);
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'pending_count')::int=0,'Legacy thread prompted');
SELECT pg_temp.check_true((public.get_my_service_reviews()#>>'{items,0,review_scope}')='legacy_relationship','Legacy scope lost');
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,1,1,%L,%L)',public.get_my_service_reviews()#>>'{items,0,id}','old',pg_temp.uid(707)),'PCR04');
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,1,%L,%L)',id,'foreign',pg_temp.uid(708)),'42501') FROM review_ids WHERE booking_id=pg_temp.uid(402);
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(405),'accepted');SELECT public.change_booking_status(pg_temp.uid(405),'completed');
SELECT public.change_booking_status(pg_temp.uid(406),'accepted');SELECT public.change_booking_status(pg_temp.uid(406),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=0,'First individual lesson counted other categories');
SELECT public.change_booking_status(pg_temp.uid(407),'accepted');SELECT public.change_booking_status(pg_temp.uid(407),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=1,'Individual second lesson missing');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(3)::text,true);
SELECT public.change_booking_status(pg_temp.uid(408),'accepted');SELECT public.change_booking_status(pg_temp.uid(408),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=0,'Another activity inherited lesson count');
RESET ROLE;
SET LOCAL ROLE anon;
SELECT pg_temp.check_error('SELECT public.get_my_service_reviews()','42501');
SELECT pg_temp.check_error('SELECT * FROM pc_private.service_review_threads','42501');
SELECT pg_temp.check_true((public.get_public_service_reviews(pg_temp.uid(5))->>'count')::int=3,'Public service feedback unavailable');
SELECT pg_temp.check_true((public.get_public_service_reviews(pg_temp.uid(5),pg_temp.uid(207))->>'count')::int=1,'Service filter mixed services');
SELECT pg_temp.check_true((public.get_public_service_reviews(pg_temp.uid(5),pg_temp.uid(207))#>>'{items,0,service_name}')='Corso nel centro','Public snapshot changed');
SELECT pg_temp.check_true(NOT EXISTS(SELECT 1 FROM jsonb_array_elements(public.get_public_service_reviews(pg_temp.uid(5))->'items') x WHERE x ?| ARRAY['professional_rating','booking_id','owner_id','end_at','notes','email']),'Public private data leaked');
SELECT pg_temp.check_true((public.get_public_service_reviews(pg_temp.uid(2))#>>'{items,0,review_scope}')='legacy_relationship','Legacy history disappeared');
SELECT pg_temp.check_error('SELECT public.get_public_service_reviews(pg_temp.uid(5),NULL,0,999)','22023');
SELECT pg_temp.check_true(EXISTS(SELECT 1 FROM public.search_public_professionals(NULL,NULL,NULL,'trainer',NULL,5) WHERE id=pg_temp.uid(5)),'Deprecated rating parameter hides centres');
RESET ROLE;
UPDATE public.professionals SET approved=false,approval_status='pending' WHERE id=pg_temp.uid(5);
SET LOCAL ROLE anon;
SELECT pg_temp.check_true((public.get_public_service_reviews(pg_temp.uid(5))->>'count')::int=0,'Unapproved activity exposed');
RESET ROLE;
SELECT pg_temp.check_true(NOT has_table_privilege('authenticated','pc_private.service_review_threads','SELECT'),'Direct access opened');
SELECT pg_temp.check_true(NOT (SELECT prosecdef FROM pg_proc WHERE oid='public.get_public_service_reviews(uuid,uuid,integer,integer)'::regprocedure),'Public SECURITY DEFINER');
SELECT pg_temp.check_true((SELECT bool_and(relrowsecurity) FROM pg_class WHERE oid IN('pc_private.review_experiences'::regclass,'pc_private.service_review_threads'::regclass,'pc_private.service_review_writes'::regclass)),'RLS missing');
ROLLBACK;
