CREATE FUNCTION pg_temp.assert_ex(ok boolean, message text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION 'FAILED: %',message; END IF;
END $$;
CREATE FUNCTION pg_temp.reject_ex(statement text, expected text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 EXECUTE statement; RAISE EXCEPTION 'Unexpected success: %',statement;
EXCEPTION WHEN OTHERS THEN IF SQLSTATE <> expected THEN RAISE; END IF; END $$;
GRANT EXECUTE ON FUNCTION pg_temp.assert_ex(boolean,text),pg_temp.reject_ex(text,text) TO anon,authenticated;
SELECT pg_temp.assert_ex(NOT EXISTS((SELECT row FROM exhibition_before_services) EXCEPT SELECT to_jsonb(s) FROM public.services s),'existing services unmodified');
SELECT pg_temp.assert_ex(NOT EXISTS((SELECT row FROM exhibition_before_bookings) EXCEPT SELECT to_jsonb(b) FROM public.bookings b),'existing bookings and notes unmodified');
SELECT pg_temp.assert_ex((SELECT professional_type='walker' FROM public.professionals WHERE id='a8100000-0000-0000-0000-000000000001'),'legacy identity retained');
SET ROLE anon;
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.search_public_professionals(p_zone_text=>'Testville')),'default trainer directly searchable');
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.search_public_professionals(p_service_type=>'boarding',p_zone_text=>'Testville')),'boarding search');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_public_professionals(p_service_type=>'sitter')),'sitting removed from API');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_public_professionals(p_service_type=>'groomer')),'grooming not in everyday search');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_exhibition_professionals(p_service_type=>'trainer')),'no training in exhibitions');
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.search_exhibition_professionals(p_zone_text=>'Testville')),'default grooming');
SELECT pg_temp.assert_ex((SELECT count(*)=1 AND bool_and((matching_services->0->>'service_type')='handler' AND jsonb_array_length(matching_services)=1 AND honor_tier IS NULL) FROM public.search_exhibition_professionals(p_service_type=>'handler',p_zone_text=>'Testville')),'handler exact service, no invented badge');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_exhibition_professionals(p_service_type=>'handler',p_max_price=>45)),'price filter');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_exhibition_professionals(p_lat=>40,p_lng=>10)),'geographic coverage');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_exhibition_professionals(p_zone_text=>'NoSuchCity')),'no fabricated local results');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.get_public_professional_services('a8100000-0000-0000-0000-000000000001')),'legacy service unavailable publicly');
SELECT pg_temp.assert_ex((SELECT count(*)=4 FROM public.get_public_professional_services('a8100000-0000-0000-0000-000000000002')),'mixed account bookable service whitelist');
SELECT pg_temp.reject_ex('select * from public.services','42501');
SELECT pg_temp.reject_ex('select * from public.search_professionals_in_context(null,null,null,null,null,null,false,null)','42501');
SELECT pg_temp.reject_ex($q$select public.save_my_calendar_service(gen_random_uuid(),'test','handler',20,60,'hourly','#D5A33A',true)$q$,'42501');
RESET ROLE;
SET ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','a8100000-0000-0000-0000-000000000002',false);
SELECT public.set_my_professional_search_modes(false,true,array['obedience']);
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_public_professionals(p_service_type=>'trainer',p_zone_text=>'Testville')),'sport-only training hidden from daily');
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.search_sport_professionals(p_discipline_id=>'obedience',p_zone_text=>'Testville')),'sport selection preserved');
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.search_public_professionals(p_service_type=>'boarding',p_zone_text=>'Testville')),'boarding independent of trainer toggle');
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.search_exhibition_professionals(p_service_type=>'handler',p_zone_text=>'Testville')),'handler independent of trainer toggle');
SELECT pg_temp.reject_ex($q$select public.save_my_calendar_service('a8100000-0000-0000-0000-000000000101','foreign','handler',20,60,'hourly','#D5A33A',true)$q$,'42501');
SELECT pg_temp.reject_ex($q$select public.save_my_calendar_service(gen_random_uuid(),'hidden sitter','sitter',20,60,'hourly','#D5A33A',true)$q$,'22023');
SELECT set_config('request.jwt.claim.sub','a8100000-0000-0000-0000-000000000001',false);
SELECT public.save_my_calendar_service('a8100000-0000-0000-0000-000000000101','Legacy walk','walker',15,60,'hourly','#047857',false);
SELECT pg_temp.reject_ex($q$select public.save_my_calendar_service('a8100000-0000-0000-0000-000000000101','walk','walker',15,60,'hourly','#047857',true)$q$,'22023');
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.bookings WHERE id='a8100000-0000-0000-0000-000000000201' AND notes='Historical private note'),'professional can still access legacy booking');
SELECT set_config('request.jwt.claim.sub','a8100000-0000-0000-0000-000000000003',false);
SELECT pg_temp.assert_ex((SELECT count(*)=1 FROM public.bookings WHERE id='a8100000-0000-0000-0000-000000000201'),'owner can still access legacy booking');
SELECT pg_temp.reject_ex($q$select public.create_booking_with_dog('a8100000-0000-0000-0000-000000000106','a8100000-0000-0000-0000-000000000301',now()+interval '2 days','No new sitting')$q$,'22023');
SELECT pg_temp.assert_ex((public.create_booking_with_dog('a8100000-0000-0000-0000-000000000105','a8100000-0000-0000-0000-000000000301',now()+interval '2 days','Handler request')).status='pending','handler booking works with verified owner');
RESET ROLE;
SELECT set_config('request.jwt.claim.sub','',false);
INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES
 ('a8100000-0000-0000-0000-000000000004','handler@example.invalid','{"pawconnect_onboarding_version":"1","full_name":"Handler","role":"professional","professional_type":"handler"}');
SELECT pg_temp.assert_ex((SELECT professional_type='handler' AND NOT approved AND approval_status='pending' FROM public.professionals WHERE id='a8100000-0000-0000-0000-000000000004'),'handler signup pending manual approval');
SELECT pg_temp.assert_ex((SELECT NOT email_verified FROM public.profiles WHERE id='a8100000-0000-0000-0000-000000000004'),'no fake email verification');
SELECT pg_temp.reject_ex($q$INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES (gen_random_uuid(),'bad@example.invalid','{"pawconnect_onboarding_version":"1","role":"professional","professional_type":"sitter"}')$q$,'22023');
INSERT INTO public.services(professional_id,name,service_type,price,duration_minutes,active) VALUES ('a8100000-0000-0000-0000-000000000004','Pending handler','handler',5,60,true);
SET ROLE anon;
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.search_exhibition_professionals(p_service_type=>'handler') WHERE id='a8100000-0000-0000-0000-000000000004'),'pending handler not public');
SELECT pg_temp.assert_ex((SELECT count(*)=0 FROM public.get_public_professional_services('a8100000-0000-0000-0000-000000000004')),'pending services not public');
RESET ROLE;
SELECT pg_temp.assert_ex(NOT (SELECT prosecdef FROM pg_proc WHERE oid='public.search_exhibition_professionals(numeric,numeric,text,text,numeric,numeric)'::regprocedure),'public API invoker only');
SELECT pg_temp.assert_ex((SELECT prosecdef AND proconfig @> ARRAY['search_path=""'] FROM pg_proc WHERE oid='pc_private.search_exhibition_professionals(numeric,numeric,text,text,numeric,numeric)'::regprocedure),'private API fixed search path');
SELECT pg_temp.assert_ex(NOT has_function_privilege('anon','pc_private.enforce_professional_activity()','EXECUTE'),'trigger not callable by client');
