BEGIN;
CREATE OR REPLACE FUNCTION pg_temp.u(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$ SELECT ('d0000000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid $$;
CREATE OR REPLACE FUNCTION pg_temp.ok(value boolean,msg text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN IF value IS DISTINCT FROM true THEN RAISE EXCEPTION 'TEST FAILED: %',msg; END IF; END $$;
CREATE OR REPLACE FUNCTION pg_temp.err(query text,expected text) RETURNS void LANGUAGE plpgsql AS $$ BEGIN
 BEGIN EXECUTE query; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=expected THEN RETURN; END IF; RAISE EXCEPTION 'Unexpected % (expected %): %',SQLSTATE,expected,SQLERRM; END;
 RAISE EXCEPTION 'Expected error %: %',expected,query; END $$;
CREATE OR REPLACE FUNCTION pg_temp.today() RETURNS date LANGUAGE sql AS $$ SELECT (now() AT TIME ZONE 'Europe/Rome')::date $$;
GRANT EXECUTE ON FUNCTION pg_temp.u(integer),pg_temp.ok(boolean,text),pg_temp.err(text,text),pg_temp.today() TO authenticated,anon;
SELECT pg_temp.ok((SELECT lifecycle='legacy' AND name_snapshot='Vecchio piano' AND period_uses IS NULL FROM public.client_subscriptions WHERE id=pg_temp.u(700)),'legacy preserved');
SELECT pg_temp.ok(pc_private.subscription_boundary('2027-01-31','month',1)='2027-02-28' AND pc_private.subscription_boundary('2027-01-31','month',2)='2027-03-31','monthly anniversary does not drift');
SELECT pg_temp.ok(pc_private.subscription_boundary('2028-01-31','month',1)='2028-02-29','leap year');
SELECT pg_temp.ok(pc_private.subscription_boundary('2026-03-28','week',1)='2026-04-04' AND pc_private.subscription_boundary('2026-10-20','fortnight',1)='2026-11-03','calendar weeks through DST');
SELECT pg_temp.ok(('2026-03-30'::date::timestamp AT TIME ZONE 'Europe/Rome')-('2026-03-29'::date::timestamp AT TIME ZONE 'Europe/Rome')=interval '23 hours','Italy DST boundary');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.u(1)::text,true);
SELECT public.save_own_subscription_plan(pg_temp.u(601),0,pg_temp.u(101),'Percorso mensile','Quattro lezioni concordate','month',4,100);
SELECT public.save_own_subscription_plan(pg_temp.u(601),0,pg_temp.u(101),'Percorso mensile','Quattro lezioni concordate','month',4,100);
SELECT pg_temp.ok((SELECT count(*)=2 FROM public.list_own_subscription_plans()),'plan creation retry');
SELECT pg_temp.err($q$SELECT public.save_own_subscription_plan(pg_temp.u(602),0,pg_temp.u(102),'Altro','', 'week',2,50)$q$,'22023');
SELECT pg_temp.err($q$SELECT public.save_own_subscription_plan(pg_temp.u(602),0,pg_temp.u(101),'Errore','', 'year',2,50)$q$,'22023');
SELECT pg_temp.err($q$SELECT public.save_own_subscription_plan(pg_temp.u(602),0,pg_temp.u(101),'Errore','', 'week',0,50)$q$,'22023');
SELECT pg_temp.err($q$SELECT public.save_own_subscription_plan(pg_temp.u(602),0,pg_temp.u(101),'Errore','', 'week',2,'NaN')$q$,'22023');
SELECT pg_temp.err($q$SELECT public.issue_client_subscription(pg_temp.u(701),pg_temp.u(601),1,pg_temp.u(13),pg_temp.today())$q$,'42501');
SELECT pg_temp.err($q$SELECT public.issue_client_subscription(pg_temp.u(701),pg_temp.u(601),1,pg_temp.u(11),pg_temp.today()-1)$q$,'22023');
SELECT pg_temp.err($q$SELECT public.issue_client_subscription(pg_temp.u(701),pg_temp.u(601),0,pg_temp.u(11),pg_temp.today())$q$,'40001');
SELECT public.issue_client_subscription(pg_temp.u(701),pg_temp.u(601),1,pg_temp.u(11),pg_temp.today());
SELECT public.issue_client_subscription(pg_temp.u(701),pg_temp.u(601),1,pg_temp.u(11),pg_temp.today());
SELECT pg_temp.ok((SELECT count(*)=2 FROM public.list_my_subscriptions(true)),'one agreement on retry');
SELECT pg_temp.ok((SELECT count(*)=1 FROM public.get_subscription_periods(pg_temp.u(701))),'one first period on retry');
SELECT pg_temp.err($q$SELECT public.issue_client_subscription(pg_temp.u(702),pg_temp.u(601),1,pg_temp.u(11),pg_temp.today())$q$,'PSB02');
SELECT pg_temp.err($q$SELECT public.issue_client_subscription(pg_temp.u(701),pg_temp.u(601),1,pg_temp.u(12),pg_temp.today())$q$,'22023');
SELECT pg_temp.ok((SELECT count(*)=1 FROM public.list_own_pass_templates()),'subscription templates hidden from packs');
SELECT pg_temp.ok((SELECT count(*)=1 FROM public.list_my_client_passes(true)),'periods not duplicated in packs');
SELECT pg_temp.err($q$SELECT public.set_own_pass_template_active(pg_temp.u(601),1,true)$q$,'42501');
SELECT pg_temp.err($q$SELECT public.save_own_pass_template(pg_temp.u(601),1,pg_temp.u(101),'Bypass','',10,20,30)$q$,'42501');
SELECT pg_temp.err($q$SELECT public.issue_client_pass(pg_temp.u(802),pg_temp.u(601),pg_temp.u(11))$q$,'PAP05');
SELECT public.save_own_subscription_plan(pg_temp.u(601),1,pg_temp.u(101),'Nuovo prezzo','Cambiano i nuovi contratti','month',6,150);
SELECT pg_temp.err($q$SELECT public.save_own_subscription_plan(pg_temp.u(601),1,pg_temp.u(101),'Stale','', 'month',1,20)$q$,'40001');
SELECT pg_temp.ok((SELECT period_uses=4 AND period_price=100 AND name='Percorso mensile' FROM public.list_my_subscriptions(true) WHERE id=pg_temp.u(701)),'terms frozen at agreement');
SELECT public.set_subscription_plan_active(pg_temp.u(601),2,false);
SELECT public.renew_client_subscription(pg_temp.u(702),pg_temp.u(701),pg_temp.u(701));
SELECT public.renew_client_subscription(pg_temp.u(702),pg_temp.u(701),pg_temp.u(701));
SELECT pg_temp.ok((SELECT count(*)=2 AND sum(total_uses)=8 FROM public.get_subscription_periods(pg_temp.u(701))),'renewal idempotent at original terms even after plan archived');
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(703),pg_temp.u(701),pg_temp.u(701))$q$,'40001');
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(703),pg_temp.u(701),pg_temp.u(702))$q$,'PSB04');
SELECT pg_temp.ok((SELECT NOT can_renew FROM public.list_my_subscriptions(true) WHERE id=pg_temp.u(701)),'only one future period');
SELECT public.record_pass_use(pg_temp.u(801),pg_temp.u(701),null,now(),'Lezione in abbonamento');
SELECT public.record_pass_use(pg_temp.u(801),pg_temp.u(701),null,now(),'Lezione in abbonamento');
SELECT pg_temp.ok((SELECT remaining_uses=3 FROM public.get_subscription_periods(pg_temp.u(701)) WHERE ordinal=0),'same shared ledger, no double debit');
SELECT pg_temp.ok((SELECT remaining_uses=4 FROM public.get_subscription_periods(pg_temp.u(701)) WHERE ordinal=1),'next balance independent');
SELECT pg_temp.err($q$SELECT public.record_pass_use(pg_temp.u(802),pg_temp.u(702),null,now(),'Troppo presto')$q$,'PAP02');
SELECT set_config('request.jwt.claim.sub',pg_temp.u(11)::text,true);
SELECT pg_temp.ok((SELECT count(*)=2 FROM public.list_my_subscriptions()),'owner sees own agreements');
SELECT pg_temp.ok((SELECT count(*)=2 FROM public.get_subscription_periods(pg_temp.u(701))),'owner sees own periods');
SELECT pg_temp.ok((SELECT count(*)=1 FROM public.get_client_pass_events(pg_temp.u(701))),'owner sees ledger');
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(703),pg_temp.u(701),pg_temp.u(702))$q$,'42501');
SELECT set_config('request.jwt.claim.sub',pg_temp.u(12)::text,true);
SELECT pg_temp.ok((SELECT count(*)=0 FROM public.list_my_subscriptions()),'other owner isolated');
SELECT pg_temp.err($q$SELECT public.get_subscription_periods(pg_temp.u(701))$q$,'42501');
SELECT set_config('request.jwt.claim.sub',pg_temp.u(2)::text,true);
SELECT pg_temp.ok((SELECT count(*)=0 FROM public.list_my_subscriptions(true)),'other professional isolated');
SELECT pg_temp.err($q$SELECT public.get_subscription_periods(pg_temp.u(701))$q$,'42501');
SELECT pg_temp.err($q$SELECT public.close_client_subscription(pg_temp.u(701),2,'Non mio')$q$,'42501');
SELECT set_config('request.jwt.claim.sub',pg_temp.u(1)::text,true);
SELECT pg_temp.err($q$SELECT public.close_client_subscription(pg_temp.u(701),1,'Versione obsoleta')$q$,'40001');
SELECT public.close_client_subscription(pg_temp.u(701),2,'Percorso concluso');
SELECT public.close_client_subscription(pg_temp.u(701),2,'Percorso concluso');
SELECT public.renew_client_subscription(pg_temp.u(702),pg_temp.u(701),pg_temp.u(701));
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(703),pg_temp.u(701),pg_temp.u(702))$q$,'PSB03');
SELECT public.record_pass_use(pg_temp.u(802),pg_temp.u(701),null,now(),'Lezioni già concordate restano valide');
SELECT public.reverse_pass_use(pg_temp.u(803),pg_temp.u(802),'Lezione registrata per errore');
SELECT pg_temp.ok((SELECT count(*)=3 FROM public.get_client_pass_events(pg_temp.u(701))),'closed renewal retains ledger and corrections');
SELECT pg_temp.ok((SELECT remaining_uses=3 FROM public.get_subscription_periods(pg_temp.u(701)) WHERE ordinal=0),'correction restores only its period');
SELECT public.cancel_own_client_pass(id,version,'Periodo aggiunto per errore') FROM public.get_subscription_periods(pg_temp.u(701)) WHERE ordinal=1;
SELECT pg_temp.ok((SELECT state='cancelled' AND remaining_uses=4 FROM public.get_subscription_periods(pg_temp.u(701)) WHERE ordinal=1),'cancel one period retains its balance and history');
SELECT pg_temp.ok((SELECT state='active' AND remaining_uses=3 FROM public.get_subscription_periods(pg_temp.u(701)) WHERE ordinal=0),'other period unaffected');
SELECT public.set_subscription_plan_active(pg_temp.u(601),3,true);
SELECT public.issue_client_subscription(pg_temp.u(704),pg_temp.u(601),4,pg_temp.u(11),pg_temp.today()+7);
SELECT pg_temp.ok((SELECT scheduled AND remaining_uses=6 AND price=150 FROM public.get_subscription_periods(pg_temp.u(704))),'new terms only on new agreement; future start');
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(705),pg_temp.u(704),pg_temp.u(704))$q$,'PSB04');
RESET ROLE;
UPDATE public.services SET active=false WHERE id=pg_temp.u(101);
SET LOCAL ROLE authenticated;
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(705),pg_temp.u(704),pg_temp.u(704))$q$,'PSB01');
RESET ROLE;
UPDATE public.services SET active=true WHERE id=pg_temp.u(101);
UPDATE public.professionals SET approved=false,approval_status='pending' WHERE id=pg_temp.u(1);
SET LOCAL ROLE authenticated;
SELECT pg_temp.err($q$SELECT public.renew_client_subscription(pg_temp.u(705),pg_temp.u(704),pg_temp.u(704))$q$,'42501');
SELECT pg_temp.ok((SELECT count(*)=1 FROM public.get_subscription_periods(pg_temp.u(704))),'history remains visible when professional approval changes');
RESET ROLE;
UPDATE public.professionals SET approved=true,approval_status='approved' WHERE id=pg_temp.u(1);
DO $$ DECLARE t text; r text; perm text; fn record; BEGIN
 FOREACH t IN ARRAY ARRAY['subscription_plans','client_subscriptions','subscription_periods'] LOOP
  PERFORM pg_temp.ok((SELECT relrowsecurity FROM pg_class WHERE oid=('public.'||t)::regclass),'RLS '||t);
  FOREACH r IN ARRAY ARRAY['anon','authenticated'] LOOP
   FOREACH perm IN ARRAY ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] LOOP
    PERFORM pg_temp.ok(NOT has_table_privilege(r,'public.'||t,perm),'no direct access '||r||t||perm);
   END LOOP;
  END LOOP;
 END LOOP;
 FOR fn IN SELECT p.oid,p.proname,p.prosecdef FROM pg_proc p WHERE p.pronamespace='public'::regnamespace AND p.proname IN
 ('list_own_subscription_plans','save_own_subscription_plan','set_subscription_plan_active','issue_client_subscription','renew_client_subscription','close_client_subscription','list_my_subscriptions','get_subscription_periods') LOOP
  PERFORM pg_temp.ok(NOT fn.prosecdef,'public invoker '||fn.proname);
  PERFORM pg_temp.ok(NOT has_function_privilege('anon',fn.oid,'EXECUTE') AND has_function_privilege('authenticated',fn.oid,'EXECUTE'),'RPC grants '||fn.proname);
 END LOOP;
 PERFORM pg_temp.ok(NOT has_function_privilege('authenticated','pc_private.add_subscription_period(uuid,public.client_subscriptions,integer,uuid)','EXECUTE'),'internal writer closed');
END $$;
SET LOCAL ROLE anon;
SELECT pg_temp.err($q$SELECT public.list_my_subscriptions()$q$,'42501');
RESET ROLE;
DELETE FROM auth.users WHERE id=pg_temp.u(1);
SELECT pg_temp.ok(NOT EXISTS(SELECT 1 FROM public.client_subscriptions WHERE professional_id=pg_temp.u(1)),'account deletion not blocked');
SELECT pg_temp.ok(NOT EXISTS(SELECT 1 FROM public.subscription_periods WHERE subscription_id=pg_temp.u(701)),'period cascade');
ROLLBACK;
