BEGIN;
CREATE FUNCTION pg_temp.check_true(ok boolean,message text) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF ok IS DISTINCT FROM true THEN RAISE EXCEPTION '%',message; END IF; END$$;
CREATE FUNCTION pg_temp.check_error(q text,code text) RETURNS void LANGUAGE plpgsql AS $$BEGIN BEGIN EXECUTE q; EXCEPTION WHEN OTHERS THEN IF SQLSTATE=code THEN RETURN; END IF; RAISE; END; RAISE EXCEPTION 'Expected error %: %',code,q; END$$;
CREATE FUNCTION pg_temp.uid(n integer) RETURNS uuid LANGUAGE sql IMMUTABLE AS $$SELECT ('e8200000-0000-0000-0000-'||lpad(n::text,12,'0'))::uuid$$;
GRANT EXECUTE ON FUNCTION pg_temp.check_true(boolean,text),pg_temp.check_error(text,text),pg_temp.uid(integer) TO authenticated,anon;
SELECT pg_temp.check_true((SELECT count(*)=0 FROM pc_private.service_review_threads),'No retrospective invitations');
SELECT pg_temp.check_true((SELECT rating=3 AND comment='RECENSIONE PRECEDENTE DA CONSERVARE' FROM public.reviews WHERE id=pg_temp.uid(501)),'Existing review rewritten');
-- Fixtures are pending; acceptance and completion use the actual authenticated API.
INSERT INTO public.bookings(id,owner_id,professional_id,service_id,start_at,end_at,status)
SELECT pg_temp.uid(n),pg_temp.uid(o),pg_temp.uid(p),pg_temp.uid(s),now()-interval '2 days',now()-interval '1 day','pending'
FROM (VALUES(401,4,2,201),(402,4,2,207),(403,4,3,204),(404,4,2,202),(405,4,2,203),(406,4,2,207),(407,1,2,207),
 (408,4,5,205),(409,4,5,205),(410,4,5,206),(411,4,2,207),(412,4,2,201),(413,4,2,207)) v(n,o,p,s);
UPDATE public.bookings SET start_at=now()+interval '1 day',end_at=now()+interval '25 hours' WHERE id=pg_temp.uid(412);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(412),'accepted');
SELECT pg_temp.check_error($q$SELECT public.change_booking_status(pg_temp.uid(412),'completed')$q$,'PCR01');
SELECT public.change_booking_status(pg_temp.uid(411),'declined');
SELECT public.change_booking_status(pg_temp.uid(401),'accepted');
SELECT public.change_booking_status(pg_temp.uid(401),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=0,'First service requested a professional review');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'count')::int=0,'First service requested an owner review');
SELECT pg_temp.check_error($q$SELECT public.submit_review(pg_temp.uid(401),5,'premature')$q$,'PCR02');
SELECT public.change_booking_status(pg_temp.uid(413),'cancelled');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(402),'accepted');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=0,'Accepted second service is not completed');
SELECT public.change_booking_status(pg_temp.uid(402),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=1,'Second service missing professional invitation');
CREATE TEMP TABLE review_test_context AS SELECT (public.get_my_service_reviews(true)#>>'{items,0,id}')::uuid AS trainer,NULL::uuid AS boarding;
RESET ROLE;
GRANT ALL ON review_test_context TO authenticated;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'pending_count')::int=1,'Second different service missing owner invitation');
SELECT public.write_service_review(trainer,0,4,'Esperienza positiva',pg_temp.uid(701)) FROM review_test_context;
SELECT public.write_service_review(trainer,0,4,'Esperienza positiva',pg_temp.uid(701)) FROM review_test_context;
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,3,''different'',%L)',trainer,pg_temp.uid(701)),'22023') FROM review_test_context;
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,3,''stale'',%L)',trainer,pg_temp.uid(702)),'40001') FROM review_test_context;
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,1,6,'''',%L)',trainer,pg_temp.uid(702)),'22023') FROM review_test_context;
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,1,4,%L,%L)',trainer,repeat('a',501),pg_temp.uid(702)),'22023') FROM review_test_context;
RESET ROLE;
CREATE TEMP TABLE review_window_before AS SELECT owner_edit_until FROM pc_private.service_review_threads WHERE id=(SELECT trainer FROM review_test_context);
SET LOCAL ROLE authenticated;
SELECT public.write_service_review(trainer,1,5,'Rettifica',pg_temp.uid(702)) FROM review_test_context;
RESET ROLE;
SELECT pg_temp.check_true((SELECT t.owner_edit_until=w.owner_edit_until FROM pc_private.service_review_threads t CROSS JOIN review_window_before w WHERE t.id=(SELECT trainer FROM review_test_context)),'Editing extended the correction window');
SELECT pg_temp.check_true((SELECT previous_value->>'comment'='Esperienza positiva' FROM pc_private.service_review_writes WHERE request_id=pg_temp.uid(702)),'Previous review version not preserved');
SET LOCAL ROLE authenticated;
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'pending_count')::int=0,'Owner prompted again');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.write_service_review(trainer,0,2,'',pg_temp.uid(703)) FROM review_test_context;
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,1,4,''private text disallowed'',%L)',trainer,pg_temp.uid(704)),'42501') FROM review_test_context;
SELECT pg_temp.check_true((public.get_my_service_reviews(true)#>>'{items,0,professional_rating}')::int=2,'Private rating not visible to author');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_true((public.get_my_service_reviews()#>>'{items,0,professional_rating}')::int=2,'Private rating not visible to client');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(1)::text,true);
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'count')::int=0,'Other owner read private votes');
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,1,'''',%L)',trainer,pg_temp.uid(705)),'42501') FROM review_test_context;
SELECT pg_temp.check_error(format('SELECT public.dismiss_service_review(%L)',trainer),'42501') FROM review_test_context;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(3)::text,true);
SELECT public.change_booking_status(pg_temp.uid(403),'accepted');SELECT public.change_booking_status(pg_temp.uid(403),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=0,'Different trainer inherited count or vote');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(404),'accepted');SELECT public.change_booking_status(pg_temp.uid(404),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=0,'Boarding prompted professional');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
UPDATE review_test_context SET boarding=(SELECT (x->>'id')::uuid FROM jsonb_array_elements(public.get_my_service_reviews()->'items') x WHERE x->>'kind'='boarding');
SELECT public.write_service_review(boarding,0,5,'Soggiorno',pg_temp.uid(706)) FROM review_test_context;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,0,5,'''',%L)',boarding,pg_temp.uid(707)),'42501') FROM review_test_context;
-- Original reviews and rating aggregates contain no private client score.
RESET ROLE;
SELECT pg_temp.check_true((SELECT count(*)=3 FROM public.reviews WHERE professional_id=pg_temp.uid(2)),'Duplicate public reviews or private score counted');
SELECT pg_temp.check_true((SELECT abs(rating-13.0/3)<0.00001 AND review_count=3 FROM public.professionals WHERE id=pg_temp.uid(2)),'Private score polluted public aggregates');
SELECT pg_temp.check_true((SELECT count(*)=3 FROM public.public_reviews WHERE professional_id=pg_temp.uid(2)),'Public projection changed');
SELECT pg_temp.check_true(NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='public_reviews' AND column_name LIKE '%professional_rating%'),'Private vote publicly exposed');
UPDATE pc_private.service_review_threads SET owner_edit_until=now()-interval '1 minute',professional_edit_until=now()-interval '1 minute' WHERE id=(SELECT trainer FROM review_test_context);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_error(format('SELECT public.write_service_review(%L,2,4,'''',%L)',trainer,pg_temp.uid(708)),'PCR03') FROM review_test_context;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(406),'accepted');SELECT public.change_booking_status(pg_temp.uid(406),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'pending_count')::int=0,'Repeated invitation after another lesson');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT public.write_service_review(trainer,2,4,'Nuova esperienza',pg_temp.uid(708)) FROM review_test_context;
RESET ROLE;
SELECT pg_temp.check_true((SELECT count(*)=3 FROM public.reviews WHERE professional_id=pg_temp.uid(2)),'An update added a fourth public vote');
SET LOCAL ROLE authenticated;
-- Attach an old review without removing it or prompting the client retrospectively.
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(407),'accepted');SELECT public.change_booking_status(pg_temp.uid(407),'completed');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(1)::text,true);
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'pending_count')::int=0 AND (public.get_my_service_reviews()#>>'{items,0,own_rating}')::int=3,'Old review not attached');
-- Centre services do not pretend to identify an individual instructor.
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(5)::text,true);
SELECT public.change_booking_status(pg_temp.uid(408),'accepted');SELECT public.change_booking_status(pg_temp.uid(408),'completed');
SELECT public.change_booking_status(pg_temp.uid(409),'accepted');SELECT public.change_booking_status(pg_temp.uid(409),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=0,'Centre incorrectly aggregated different instructors');
SELECT public.change_booking_status(pg_temp.uid(410),'accepted');SELECT public.change_booking_status(pg_temp.uid(410),'completed');
SELECT pg_temp.check_true((public.get_my_service_reviews(true)->>'count')::int=1 AND (public.get_my_service_reviews(true)->>'pending_count')::int=0,'Centre boarding invalid');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT public.dismiss_service_review((SELECT (x->>'id')::uuid FROM jsonb_array_elements(public.get_my_service_reviews()->'items') x WHERE x->>'booking_id'=pg_temp.uid(410)::text));
SELECT pg_temp.check_true((public.get_my_service_reviews()->>'pending_count')::int=0,'Dismissed reminder still active');
-- Existing owner-only handler/groomer API remains available, with safe retry.
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(405),'accepted');SELECT public.change_booking_status(pg_temp.uid(405),'completed');
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(4)::text,true);
SELECT pg_temp.check_true(public.get_legacy_review_bookings(ARRAY[pg_temp.uid(405),pg_temp.uid(401)])=ARRAY[pg_temp.uid(405)],'Legacy UI bypassed training threshold');
SELECT public.submit_review(pg_temp.uid(405),4,'Toelettatura');SELECT public.submit_review(pg_temp.uid(405),4,'Toelettatura');
SELECT pg_temp.check_true(cardinality(public.get_legacy_review_bookings(ARRAY[pg_temp.uid(405)]))=0,'Reviewed service still prompted');
RESET ROLE;
SELECT pg_temp.check_true((SELECT status='accepted' FROM public.bookings WHERE id=pg_temp.uid(412)),'Premature completion persisted');
SELECT pg_temp.check_true(NOT has_table_privilege('authenticated','pc_private.service_review_threads','SELECT') AND NOT has_table_privilege('anon','pc_private.service_review_writes','SELECT'),'Direct private access');
SELECT pg_temp.check_true((SELECT bool_and(relrowsecurity) FROM pg_class WHERE oid IN('pc_private.review_experiences'::regclass,'pc_private.service_review_threads'::regclass,'pc_private.service_review_writes'::regclass)),'RLS missing');
SELECT pg_temp.check_true(NOT (SELECT prosecdef FROM pg_proc WHERE oid='public.write_service_review(uuid,integer,integer,text,uuid)'::regprocedure),'Public definer introduced');
-- Reclassifying a service after acceptance must not change the review rules.
INSERT INTO public.bookings(id,owner_id,professional_id,service_id,start_at,end_at,status) VALUES
 (pg_temp.uid(414),pg_temp.uid(1),pg_temp.uid(2),pg_temp.uid(201),now()-interval '2 days',now()-interval '1 day','pending');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub',pg_temp.uid(2)::text,true);
SELECT public.change_booking_status(pg_temp.uid(414),'accepted');
RESET ROLE;
UPDATE public.services SET service_type='boarding' WHERE id=pg_temp.uid(201);
SET LOCAL ROLE authenticated;
SELECT public.change_booking_status(pg_temp.uid(414),'completed');
RESET ROLE;
SELECT pg_temp.check_true((SELECT service_type='trainer' FROM pc_private.review_experiences WHERE booking_id=pg_temp.uid(414)),'Accepted category was not frozen');
SELECT pg_temp.check_true((SELECT kind='trainer' FROM pc_private.service_review_threads WHERE latest_booking_id=pg_temp.uid(414)),'Catalog edit enabled a boarding review');
SET LOCAL ROLE anon;
SELECT pg_temp.check_error('SELECT public.get_my_service_reviews()','42501');
SELECT pg_temp.check_error('SELECT * FROM pc_private.service_review_threads','42501');
ROLLBACK;
